# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
python:
    - "3.6"
sudo: required
env:
    - ES_VERSION=6
    - ES_VERSION=6 DATABASE=postgresql
    - ES_VERSION=OPEN_DISTRO

services:
  - postgresql
  - docker

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database guillotina;' -U postgres

cache:
  directories:
    - eggs
install:
  - pip install flake8 codecov
  - pip install -e .[test]
script:
  - flake8 guillotina_elasticsearch --config=setup.cfg
  - pytest --cov=guillotina_elasticsearch -v --cov-report term-missing guillotina_elasticsearch
after_success:
  - codecov
