# we want to make sure it is run on trusty where sudo is provided for postgres
dist: xenial
language: python
python:
    - "3.7"
sudo: required
env:
  - DATABASE=DUMMY
  - DATABASE=postgresql

services:
  - postgresql
  - docker

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database guillotina;' -U postgres

cache:
  directories:
    - eggs
install:
  - pip install flake8 codecov
  - pip install git+https://github.com/plone/guillotina.git@master
  - pip install -e .[test]
script:
  - flake8 guillotina_elasticsearch --config=setup.cfg
  - pytest --cov=guillotina_elasticsearch -v --cov-report term-missing guillotina_elasticsearch
after_success:
  - codecov
